#!/usr/bin/env bash

killall -9 xfsettingsd picom polybar mpd dunst ksuperkey xfce4-power-manager nm-applet caffeine

nitrogen --set-zoom-fill --random ~/Media/Wallpapers

xfce4-power-manager &

exec picom &
exec dunst &
exec thunar --daemon &
exec nm-applet &

#exec caffeine &

ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

xfsettingsd &

bash ~/.config/scripts/battery-status.sh &
bash ~/.config/polybar/launch.sh &

#alacritty -e tty-clock -t -c &

exec xautolock -detectsleep -time 5 -locker "/home/davidb/Applications/bin/lock" -notify 30 -notifier "notify-send -u critical -t 10000 -- 'Locking Screen in 30 sec'" &
exec xidlehook --not-when-audio --not-when-fullscreen --timer 1200 "systemctl suspend" - &
